### ISSUE TITLE
How to make items selected

### ISSUE THREAD

**Issue by leemour** [Magicsuggest/magicsuggest#131]
Could you please explain how can I set a selected value? I have an array of items, that I assign to `data` and I want to show some of them already selected (when editing entry). I tried this:

``` javascript
$(function() {
  $('.suggest-tag').magicSuggest({
    allowFreeEntries: true,
    data: ['London', 'Paris', 'Barcelona'],
    value: ['Moscow']
  });
});
```

But nothing is selected. I also don't know the number of item I want to select, so I can't use `value: [1,2]` and even when I use it doesn't work.

**Comment by stan74fr** [comment]
Hi Nicolas,
Also experimenting this issue when retrieving data from json file. Strangely enough I can load them once (form creation) but this shows up when I am trying to edit the form. As a consequence the values from the selector are not showing up. 

Was a fix pushed at the end? Many thks.

------------------------
function isArrayLike( obj ) {

	// Support: iOS 8.2 (not reproducible in simulator)
	// `in` check used to prevent JIT error (gh-2145)
	// hasOwn isn't used here due to false negatives
	// regarding Nodelist length in IE
	var length = !!obj && "length" in obj && obj.length,
		type = jQuery.type( obj );

	if ( type === "function" || jQuery.isWindow( obj ) ) {
		return false;
	}

	return type === "array" || length === 0 ||
		typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
