### ISSUE TITLE
Disable maxSelectionRenderer 

### ISSUE THREAD

**Issue by evermel** [Magicsuggest/magicsuggest#150]
When maxSelection is set to 1 (so when you use magicsuggest as an inputbox), maxSelectionRenderer display "You cannot choose more than 1 item".
When you have a form with multiple select, you see this sentence everywhere, overloading your form design.

I don't found how to disable this message sent to maxSelectionRenderer... is there a way to do that ?

**Comment by createam** [comment]
Thanks for providing the option. 

Can you please document the maxSelectionRenderer option? I could not find it here, http://nicolasbize.com/magicsuggest/doc.html

**Comment by RationalEar** [comment]
Had the same problem. Thanks for your posts

**Comment by Braintelligence** [comment]
Thanks for pointing out, that maxSelectionRenderer expects a function instead of a string. Please add this to the docs sometime.
:+1:
