### ISSUE TITLE
Submission Formatting

### ISSUE THREAD

**Issue by J-who** [Magicsuggest/magicsuggest#158]
Hello!
I've been trying to get this plugin working with Symfony (Many-to-Many Relationship). The last issue I'm dealing with is how this pluigin submits the data, and what Symfony wants.

```
["tags"]=>
array(2) {
  [0]=>
  string(6) "canada"
  [1]=>
  string(7) "alberta"
}
```

And Symfony wants it in this format:

```
["tags"]=>
array(2) {
  [0]=>
  array(1) {
    ["name"]=>
    string(6) "canada"
  }
  [1]=>
  array(1) {
    ["name"]=>
    string(7) "alberta"
  }
}
```

Form:

```
{{ form_widget(form.tags, { 'attr': {'class': 'magicsuggest'} }) }}
<script>
    $(function () {
        $('.magicsuggest').magicSuggest({
            useCommaKey: true,
            name: 'course_info[tags]',
            id: '[name]',
            resultsField: 'name',

            value: {{course.displaytags|json_encode|raw}},

            valueData: {{course.displaytags|json_encode|raw}},
            data: {{tags|json_encode|raw}}

        });
    });
</script>
```

Is there an easy way to slap the name data into that name array on submission?

Thanks!

**Comment by sergionegri** [comment]
I'm facing the same situation. Considering that Bootstrap is the preferred framework for Symfony (the only one for which the form theming is supported), the natural extension is having this amazing combo box working on Symfony. If you could point us on where we might touch the code to format data the Symfony way it would be amazing!
