### ISSUE TITLE
can NOT enter "<" on German keyboard with 1.3.1

### ISSUE THREAD

**Issue by ralfbecker** [Magicsuggest/magicsuggest#178]
Trying to enter eg. "Ralf Becker rb@stylite.de" does NOT work, as "<" on a German keyboard is without shift and keycode of both "," and "<" is 188. 

Following fix checks e.originalEvent.keyIdentifier != "U+002C" to allow for that:
http://svn.stylite.de/viewvc/egroupware/trunk/phpgwapi/js/jquery/magicsuggest/src/magicsuggest-1.3.1.js?r1=48953&r2=48952&pathrev=48953

Fix has been tested with latest versions of Chrome, Firefox, Safari and IE.

Please let me know if you prefer a pull request ...

Ralf

**Comment by aburikin** [comment]
Try to enter "Б" on russian keyboard (188 keycode). The same problem. Can you suggest any solution? ))

**Comment by ralfbecker** [comment]
If you use an old version, have a look for my patch mentioned above, or better update to current version.

Ralf

**Comment by aburikin** [comment]
Hello, thank you for answer.
Version that using:
 * Author:       Nicolas Bize
 * Created:      Feb 8th 2013
 * Last Updated: May 17th 2014
 * Version:      2.0.0

magicsuggest.js code:
...
case 13:case 9:case 188:// enter, tab, comma
if(e.keyCode !== 188 || cfg.useCommaKey === true) {
...

I can just comment "case 188", but it's not "true"...
