### ISSUE TITLE
Option 'resultAsString' has no effect.

### ISSUE THREAD

**Issue by matthewgrzegorczyk** [Magicsuggest/magicsuggest#189]
Hello,

I am trying to implement MagicSuggest in my project.
In my use case I want to use it as an AutoComplete feature. My config looks like this:

```
var ms = $('#test').magicSuggest({
        resultAsStringDelimiter: ';',
        resultAsString: true,
        name: 'test',
        allowFreeEntries: false,
        maxSelection: 1,
        data: ['test1', 'test2', 'test3', 'test4'],
        placeholder: 'Choose an option.'
    });
```

I wanted to get result as string, but unfortunately all the results are passed as an array all the time and I have no idea why.

**Comment by simogeo** [comment]
any reply on this ? how to get value as string and not array ?

**Comment by matthewgrzegorczyk** [comment]
I've closed this issue as it was very old, and outdated.
