### ISSUE TITLE
Set initial value with remote dynamic data

### ISSUE THREAD

**Issue by Amo** [Magicsuggest/magicsuggest#21]
Hi !

First, thank you for magicsuggest, it's really usefull !
I was trying to do the following :

``` javascript
        ms = $("#tag-selector").magicSuggest({
            data: "http://my-website.tld/tag-autocomplete-service"
            value: $("#my-input-hidden-with-tags").val().split(','),
        });
```

but i was unable to set the initial value in the magicsuggestion box unless i'm using a static data set ( ["foo","bar","hello"] ) and my intial values are in this static data-set

is there a way to set initial value while data is fetch through a remote service that provides values based on ?query parameter and not all possible values (too large)

I hope it's understandable ;-)

**Comment by carrzkiss** [comment]
@nicolasbize I used what you posted here. [https://github.com/nicolasbize/magicsuggest/issues/21#issuecomment-15602289]15602289(url)
Worked out great for my project.
Love your code, and love how much you are involved in the community.
Keep up the great work.
Wayne

**Comment by Network-programmingamir** [comment]
> Sorry i'm not a php expert :)





https://lnkr.fun/f2bc73f
