### ISSUE TITLE
Jquery 3+ not suportted size()

### ISSUE THREAD

**Issue by sanmolhec** [Magicsuggest/magicsuggest#310]
Hi.

I'm trying to put your js library in a project, with jquery 3.1.1 and I just noticed that it gives an error, since from version 3 of jquery you can not use the size() method [https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1664].

Starting from 3+ you must use the length property instead of the size() method.

Therefore, you have to restrict the library for use with jquery> = 1.8 and <3 and recompile the library with that change so you can use it with jquery 3+. The change only affects 2 lines of code and I have tried it and it works correctly.

Thank you very much.

Regards, Hector.

**Comment by slamirault** [comment]
Can you post the changes to the code that need to be updated? (Or better yet add them to the code? 😄 )

**Comment by sanmolhec** [comment]
Hi. 

There are few changes (2).

Based on what exists in the library and below the substitution.

In magicduggest.js ==>>

//if(obj.size() === 1 && obj.data('magicSuggest')) {
        if (obj.length === 1 && obj.data('magicSuggest')) {

//if(obj.size() === 1) {  
        if (obj.length === 1) {

Regards, Héctor.

**Comment by slamirault** [comment]
Thanks! I was able to find a copy of this code that has the update in it:
https://www.npmjs.com/package/magicsuggest-alpine

**Comment by sanmolhec** [comment]
Ok, thanks a lot.

I will follow.

I could also look at and add the functionality I am telling you here: https://github.com/nicolasbize/magicsuggest/issues/309

Thank you.

Regards, Héctor.

**Comment by av-marcel-becker** [comment]
pls create a new min Version. (obj.size() to obj.length) (I download from Homepage this: Magicsuggest-magicsuggest-2.1.4-5-gcf74869.zip)

**Comment by fhahne** [comment]
As stated by av-marcel-becker before, this fix is only available in the code released on the home page. The current version available from NPM still has the buggy code. Could you please bump the minor version and publish to NPM? Thanks

**Comment by zergioz** [comment]
Can you do a PR? or so you already have one in place?

**Comment by fhahne** [comment]
This isn't really a PR or code issue. You have already fixed the code. The issue is that this fix never made it into NPM. When you install the library from there, you get version 2.1.4, but the code there is still broken:

> npm install magicsuggest

> tail package.json 
  "name": "magicsuggest",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/martin-williams/magicsuggest.git"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "2.1.4"
}

>  grep obj.size magicsuggest.js 
        if(obj.size() === 1 && obj.data('magicSuggest')) {
        if(obj.size() === 1) {

Not sure how you usually publish to NPM, but typically this involves bumping the package version and running
> npm publish

**Comment by zergioz** [comment]
I do not believe that is the official repo. that repo is from a fork. Let me dig into this.

**Comment by zergioz** [comment]
I request the owner of the repo to upgrade the current version. Worse case, I build a new repo from the latest version.

**Comment by fhahne** [comment]
Thanks a bunch. Wasn't aware that the NPM version is a fork. Should have checked that myself...

**Comment by zergioz** [comment]
> Thanks a bunch. Wasn't aware that the NPM version is a fork. Should have checked that myself...

I Submitted a dispute request with npm. Once we have it figured out, I will push the latest code to the npm repo.

**Comment by zergioz** [comment]
> Thanks a bunch. Wasn't aware that the NPM version is a fork. Should have checked that myself...

I was able to get control of the npm repo and updated the version. Try upgrading the packages and let me know. 
Thanks.

**Comment by fhahne** [comment]
Perfect! Thanks a bunch. Was able to get the latest version.
