### ISSUE TITLE
JS execution

### ISSUE THREAD

**Issue by Krezalis** [Magicsuggest/magicsuggest#338]
Paste <script>alert(1)</script> in field, and JS code will be executed/
<img width="686" alt="5345" src="https://user-images.githubusercontent.com/4151282/66922137-25cf9100-f02f-11e9-99bf-10d04234792b.png">

**Comment by Krezalis** [comment]
Any updates?

**Comment by zergioz** [comment]
Is that an arbitrary js execution? 
_Sorry, I just started supporting the tool a few weeks ago and it is the first time I see this issue._

**Comment by zergioz** [comment]
> Any updates?

Pull the latest version from the master branch and let me know how it works. I will make a small release with the patch.

**Comment by Krezalis** [comment]
Tested - no execution. Thank you!

**Comment by Krezalis** [comment]
Tested - no execution. Thank you!
