### ISSUE TITLE
search on multiple fields (expanded)

### ISSUE THREAD

**Issue by dustinandband** [Magicsuggest/magicsuggest#346]
In response to https://github.com/Magicsuggest/magicsuggest/issues/80

The ryanrca's[ comment](https://github.com/Magicsuggest/magicsuggest/issues/80#issuecomment-209265079)  is still an issue, and it looks like if you paste in a full name the result doesn't show up while `mode: 'remote'` is set.

Demonstration:
https://youtu.be/2bnCtFnpgOw

**Comment by zergioz** [comment]
@dustinandband , could you post your front end code implementation.

**Comment by dustinandband** [comment]
Since there where some dependency files that had to be included I went ahead and uploaded it here
https://github.com/dustinandband/example

**Comment by zergioz** [comment]
Thank you.

**Comment by zergioz** [comment]
Try the following. In the _magicsuggest.js_ file change the values below:
```
 /*** Amount (in ms) between keyboard registers. */
typeDelay: 0
 
/*** Set starting state for combo. */
expanded: true

```
Let me know how it works. I ran a test and it worked well.

**Comment by dustinandband** [comment]
On second thought, it looks like the bug happens even when `mode: remote` is not set. Maybe I set one of the parameters wrong?
Example before & after toggling your suggestions: (when pasting a full name no results show up): https://youtu.be/0bKE6BJPpKI

One other thing I'm noticing is when `mode: remote` is set, the search input doesn't automatically toggle the focus to the correct location ([demonstration](https://youtu.be/6WcuNrYeYOI)). Based off nicolasbize's [comment](https://github.com/Magicsuggest/magicsuggest/issues/80#issuecomment-43054401) I'm guessing the developers intended it that way. Though that's unfortunate

**Comment by zergioz** [comment]
I'd say so. And the way you are implementing the solution, you will be better off using as `mode: local` I will probably be working on making more robust remote calls. As for now, the `remote and local` implementations work fine as is. 
I will be closing this issues if everything is good to go.
