### ISSUE TITLE
On Blur event is not hitting immediately !

### ISSUE THREAD

**Issue by yaswanth1121997** [Magicsuggest/magicsuggest#347]
I have a form which is having submit button ... the user typed some new tag in magic suggest and without pressing tab or enter, he directly clicked submit button... in that case firstly submit click action or any checkbox click is taking place and later the blur event is taking place (other events are triggered prior to the blur event) ... I want to use blur event so that even if the user looses focus or by clicking submit directly without pressing enter key or tab key... I can get the selection.

**Comment by zergioz** [comment]
I ran a few tests. In my opinion, the best option is to force the user to select an item. You can accomplish that by disabling the submit-button and enable it when data is selected. There is are hidden input fields created when the user selects an item.  Use it in conjunction with custom "eventHandler" to accomplish such behavior.
