### ISSUE TITLE
Single select with simple text instead of Item 

### ISSUE THREAD

**Issue by crirus** [Magicsuggest/magicsuggest#349]
Is it possible to convert this to a single select that can be used for autocomplete on a search box?
The item rendered should be a simple text and the x to delete to be on the right of the input box.

![image](https://user-images.githubusercontent.com/642060/116534280-ffa8d380-a8ea-11eb-8916-a4400cd7b172.png)

**Comment by zergioz** [comment]
That should work by default. I will have to check the code the get back to you.
