### ISSUE TITLE
Global config for all magicsuggests

### ISSUE THREAD

**Issue by getupkid** [Magicsuggest/magicsuggest#354]
Hello,
I couldn't see this in the documentation.
Is there are way to set a global config parameter that all magic suggests inherit in a project so that one doesn't need to specify it each time they instantiate and new magic suggest? 

e.g.
$.magicSuggest({
 maxDropHeight: 300
});

// Now all magicSuggests that I instantiate will have maxDropHeight: 300 automatically applied.

Cheers.

**Comment by zergioz** [comment]
Not as of yet, but it could be implemented.
