### ISSUE TITLE
jQuery 4Beta Changes

### ISSUE THREAD

**Issue by stack-its** [Magicsuggest/magicsuggest#357]
I noticed that in jQuery4 beta the following need to get updated in MagicSuggest:

$.isArray  to  Array.isArray()
$.trim       to  variable.trim()
$.proxy    to  variable.bind(handler)

There might be other deprecations, but that is what I found today.

Please let me know if I could change those myself & what the variables would be.
Thanks.

**Comment by zergioz** [comment]
Please do. And I'll merge it. Thanks for the help.

**Comment by stack-its** [comment]
I've never merged before so this is new to me ;)
I'm looking at v2.1.4, as that is what I'm running right now, but I need to understand the proxy calls a bit better.
Here's an example: ms.container.on('focus', $.proxy(handlers._onFocus, this));

So is ms.container getting a proxy added to it?  If so, would this work?
ms.container.on('focus', ms.container.bind(handlers._onFocus, this));
Let me know.  Thanks.

**Comment by zergioz** [comment]
You don't have to merge. 
1) Clone the repo
2) Make a branch
3) Push the branch
4) Create a Pull Request

I will review and merge or make changes as needed.

**Comment by stack-its** [comment]
I still need an answer about that example line of code, so I know if it's written properly.

**Comment by stack-its** [comment]
Just curious how close you are to patching these issues?
Thanks.

**Comment by zergioz** [comment]
Im working on getting pushed by the end of the week.

**Comment by zergioz** [comment]
Download the following branch and let me know how it works: https://github.com/Magicsuggest/magicsuggest/tree/jquery-deprecated-updates.

**Comment by stack-its** [comment]
Yes I downloaded the branch that you linked above & here it is in the magicsuggest.min.js file on line #47: (P.S. shouldn't be lines in min file except for the credits at beginning)

<img width="854" alt="in_min_js" src="https://github.com/Magicsuggest/magicsuggest/assets/1207542/a94246e3-3025-420f-a319-c26e4f0bc98a">

**Comment by zergioz** [comment]
Don't use the Minified version. I need to erase that thing.

**Comment by stack-its** [comment]
Ok, the full version seems to run fine.  Will it be long before this version gets released or are you still working on stuff?  Thanks

**Comment by zergioz** [comment]
I am still working on cleaning up the code, but I will probably release a minor version later this week.
PS: I was waiting for your feedback before making more changes.
