### ISSUE TITLE
how to search on multiple fields

### ISSUE THREAD

**Issue by pcbldi** [Magicsuggest/magicsuggest#80]
Hello,

is there a way I can populate the combo list by searching on multiple fields , for example , for the data - 

[ {name:"john",age:"35"}, {name:"jack",age:35"}], 

is there a way that the combo list shows the result based on searching on both name and age field.?

**Comment by ryanrca** [comment]
This does work, but it creates a new issue.  The dropdown list displays items that are already selected.

This would be challenging to solve serverside.  Unless there is an easy way to pass select items back up to server.
