### ISSUE TITLE
How tio determione item value or text on close event to send to server

### ISSUE THREAD

**Issue by codingartist** [Magicsuggest/magicsuggest#95]
Hi,
I am using ms in a one page application. I've got it working fine for adding items to selection. When a user closers just one item in the selected list, I need to send that items value (or id) to to the server with ajax so item can be removed from database. I've tried everything I can think of and no luck. The closest I can get is a list of ALL selected items, not the single item that is being closed. 

$(".ms-close-btn").bind("click",function(event) {
    // clicked item in selected list has no distinct value
        / /  only class ='ms-close-btn'

  How can i determine the value or name of the particular item in selected list who's close button (x) has just been clicked - for removal from the selected item list?

Thanks for any help anyone might have.

**Comment by fperniavp** [comment]
It would be nice to have the getValue() method accessible without tracking an event in order to get the current value.

Something like:

```
var ms = $('#ms-getValue').magicSuggest({...});
ms.getValue();
```
What if I have several inputs using magicSuggest, do I have to track their changes into a list or something in order to get their values?
